on:
  workflow_call:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out source repository
        uses: actions/checkout@v7
      - name: Set up Java
        uses: actions/setup-java@v5
        with:
          java-version: "21"
          distribution: "temurin"
      - name: Build project
        run: mvn clean verify
      - name: Run reqstool status command
        run: |
          pip install reqstool
          reqstool status local -p "$GITHUB_WORKSPACE"/docs/reqstool
