on:
  workflow_call:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        reqstool-source: [pypi, main]
    steps:
      - name: Check out source repository
        uses: actions/checkout@v7.0.1
      - name: Set up Java
        uses: actions/setup-java@v5.7.0
        with:
          java-version: "21"
          distribution: "temurin"
      - name: Build project
        run: mvn clean verify
      - name: Install reqstool
        uses: reqstool/.github/.github/actions/install-reqstool@5bdf4e5c4af98274c44c8fbaa5b54d605a6cf38a # main 2026-06-22
        with:
          reqstool-source: ${{ matrix.reqstool-source }}
      - name: Validate reqstool spec completeness
        # not yet available in the latest PyPI release
        if: matrix.reqstool-source == 'main'
        uses: reqstool/.github/.github/actions/validate-reqstool@5bdf4e5c4af98274c44c8fbaa5b54d605a6cf38a # main 2026-06-22
      - name: Run reqstool status
        uses: reqstool/.github/.github/actions/reqstool-status@5bdf4e5c4af98274c44c8fbaa5b54d605a6cf38a # main 2026-06-22
        with:
          # this repo intentionally has incomplete requirements (it showcases every status outcome)
          fail-if-incomplete: "false"

  validate-openspec:
    uses: reqstool/.github/.github/workflows/common-validate-openspec.yml@5bdf4e5c4af98274c44c8fbaa5b54d605a6cf38a # main 2026-06-22
